
import subprocess
import os

def main():

    calling_path = os.path.dirname(__file__)

    vivado_path = 'C:/Xilinx/2025.1/Vivado/bin/vivado.bat'
    tcl_script_path = f'{calling_path}/simulation_helper_script/run_simulation.tcl'

    project_dir = f'{calling_path}/../vivado_project'
    xsim_folder = f'{project_dir}/AES_256_CTR.sim/sim_1/behav/xsim'
    project_path = f'{project_dir}/AES_256_CTR.xpr'

    num_aes_cores = 1
    keystream_buffer_size = 3
    iv_counter_width = 32

    command = f'{vivado_path} -mode batch -source {tcl_script_path} -tclargs {num_aes_cores} {keystream_buffer_size} {iv_counter_width} {project_dir} {xsim_folder} {project_path}'

    os.chdir('simulation_helper_script')
    if not os.path.isdir('autogenerated_trash'):
        os.mkdir('autogenerated_trash')
    os.chdir('autogenerated_trash')

    res = subprocess.check_output(command)


if __name__ == '__main__':
    main()